services: 
  db: 
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: event_ops_db

    ports:
      - "5432:5433"
    volumes:
      - db_data:/var/lib/postgresql/data
    
volumes:
  db_data:
    driver: local
